export const LOAD_USER = "LOAD_USER";
export const LOGIN_USER = "LOGIN_USER";
export const LOGOUT_USER = "LOGOUT_USER";
export const REGISTER_USER = "REGISTER_USER";
export const UNREGISTER_USER = "UNREGISTER_USER";

// error types

export const ADD_ERRORS = "ADD_ERRORS";
export const REMOVE_ALL_ERRORS = "REMOVE_ALL_ERRORS";
export const AUTOMATICALLY_REMOVE_SOME_ERRORS = "AUTOMATICALLY_REMOVE_SOME_ERRORS";